### ISSUE TITLE
Creating a handler

### ISSUE THREAD

**Issue by Darktilldawn** [gravityfox/FoxGuard#3]
It's probably me doing something wrong, I can create a reigon and see it on the list, and details about the region. When I try creating a handler for the region I get Not a valid category! handler.
Are you able to bind a tool to your position settings? Like world edit does with the Wooden Axe.
Using
-Spongeforge Dev 848
-Forge 1577

**Comment by Darktilldawn** [comment]
Found it out, didn't read you changed it to flagsets instead of handlers.

**Comment by gravityfox** [comment]
It's actually the other way around, but yeah. 
FlagSets are now called Handlers.

**Comment by Darktilldawn** [comment]
Yeah I was confused on that part >.< I can create and link and do all that fun stuff, But what are the actual argument's I can put into flagsets? Or is that still WIP? and I didn't find much explanation on the different styled handler's you can make.

**Comment by gravityfox** [comment]
Yeah, I haven't actually documented that yet. the code is in place, but just no docs. I'll get to it soon.

If you have a specific question, ask on the forums. It's better that I answer questions there.
