### ISSUE TITLE
Corrupted world? I think.

### ISSUE THREAD

**Issue by Darktilldawn** [gravityfox/FoxGuard#5]
Well, I added your new version of FoxGuard to my test server(Thank god) and when I started the server up i get sent this error and crash
 - http://pastebin.com/mnvgips4

I then removed the mod and deleted all the configs and tried to start the server up again and it sent me same error and crashed. So I deleted my world folder, readded the mod and tried again. It worked after that. Is it the mod that caused it or something else?

**Comment by Darktilldawn** [comment]
I lied when I said it worked. When I tried logging into server I get instantly timed out with this error message in console.

- http://pastebin.com/gCmEqVxf

**Comment by gravityfox** [comment]
Give **[this build](http://gravityfox.net/builds/foxguard/foxguard-0.10.2-1-SNAPSHOT.jar)** a try. I didn't want to push out a separate release.

**Comment by Darktilldawn** [comment]
Alright one second

**Comment by Darktilldawn** [comment]
Yup everything seems to be working good now, No issues and can use all the commands

**Comment by gravityfox** [comment]
Yay. So that version is the current release now.

**Comment by Darktilldawn** [comment]
Also would you be able to post on your Title for the mod what version of SpongeForge your using? So I can make sure I'm using the right one and not causing corruptions or any messed up data

**Comment by gravityfox** [comment]
Good question.
Short answer: No.
Long answer: I actually don't know what version of SpongeForge i'm on. I actually build straight from the SpongeForge Github repository, and i'm using the api from the maven repository.
You are best off just checking the date and time my plugin was released, and using a build of SpongeForge built from around that time.

**Comment by Darktilldawn** [comment]
Ahh alright sounds good to me, I'll keep on eye on the changelogs for SpongeForge and see what's updated each version and if any of the changes would affect your mod

**Comment by gravityfox** [comment]
The only changes that would affect my plugin are API changes / Common bugs related to things that my plugin depends on. Testing on a test server is likely the only way you'll know that it will work.

However the chance that a build of sponge will break my plugin and ONLY my plugin is really slim.

**Comment by Darktilldawn** [comment]
Yeah I've learned to use a test server from now on >.< Learned that hard way on that but thankfully I was able to save what I needed to. Well the other plugins I use on Sponge the Dev updates to the new version of Sponge every time it would cause a break in his plugin, so I wouldn't be able to really check that it broke all the plugins. But test server solves everything
